# Generated by Django 6.0.2 on 2026-02-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('opcion_principal', models.CharField(max_length=50)),
                ('pregunta1', models.TextField()),
                ('pregunta2', models.CharField(max_length=10)),
                ('pregunta2_detalle', models.TextField(blank=True, null=True)),
                ('pregunta3', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('pregunta5', models.TextField()),
                ('pregunta6', models.CharField(max_length=50)),
                ('pregunta7', models.BooleanField(default=False)),
                ('pregunta8', models.BooleanField(default=False)),
                ('pregunta9', models.BooleanField(default=False)),
                ('pregunta10', models.BooleanField(default=False)),
                ('pregunta11', models.BooleanField(default=False)),
                ('pregunta12', models.BooleanField(default=False)),
                ('imagen', models.ImageField(upload_to='user_survey_images/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminSurvey',
        ),
    ]
