# Generated by Django 6.0.2 on 2026-03-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_usersurvey_delete_adminsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='pregunta10',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='pregunta11',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='pregunta12',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='pregunta7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='pregunta8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='pregunta9',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
